version: "3.8"

services:
  db:
    image: postgres:15
    container_name: football_postgres
    restart: always
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: football
      POSTGRES_PASSWORD: footballpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: football_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=football
      - DB_PASS=footballpass
      - DB_NAME=football_db
    volumes:
      - .:/usr/src/app
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:

