services:
  - type: web
    name: football-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: football-postgres
          property: connectionString
      - key: RENDER
        value: "true"

databases:
  - name: football-postgres
    plan: free 